services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DB_HOST=postgres-test
      - DB_PORT=5432
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_NAME=test_db
      - DB_SSLMODE=disable
    depends_on:
      postgres-test:
        condition: service_healthy
    volumes:
      - ./test/testdata:/app/testdata

  postgres-test:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test_db"]
      interval: 5s
      timeout: 3s
      retries: 5